AWSTemplateFormatVersion: "2010-09-09"

Description: Helper Scripts demo

Parameters:
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: The ID of the AMI.
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    # Add CreationPolicy
    
    Properties:
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      ImageId: !Ref AmiID
      InstanceType: t2.micro
      UserData: 
        # Update the UserData
        
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          packages:
            # Add packages to be installed
            
          files: 
            # Add files to be created
          
          services:
            # Add services to be started
          
          
  WebServerEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref WebServerInstance
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Enable HTTP access via port 80'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0