AWSTemplateFormatVersion: "2010-09-09"

Description: Return values demo

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Purpose
          Value: AWS CloudFormation Workshop

# Place the Outputs section